export const projectsData = [
  {
    title: "Portfolio Website",
    description: "A personal portfolio built with Next.js and Tailwind CSS.",
    image: "/images/6385a7093f7e6.jpg",
    github: "https://github.com/username/portfolio",
    live: "https://your-portfolio.com",
    category: "Next.js",
  },
  {
    title: "E-commerce Store",
    description: "Full-stack store using Next.js, Stripe, and MongoDB.",
    image: "/images/about.png",
    github: "https://github.com/username/ecommerce",
    live: "https://ecommerce-demo.com",
    category: "Fullstack",
  },
  {
    title: "Landing Page",
    description: "Animated landing page with Framer Motion and Tailwind CSS.",
    image: "/images/s1.png",
    github: "https://github.com/username/landing-page",
    live: "https://landing.example.com",
    category: "Frontend",
  },
  {
    title: "Admin Dashboard",
    description: "A responsive admin dashboard using Chart.js and Tailwind.",
    image: "/images/6385a7093f7e6.jpg",
    github: "https://github.com/username/admin-dashboard",
    live: "#",
    category: "Frontend",
  },
  {
    title: "Blog Platform",
    description: "A blog platform using Next.js, Sanity, and Tailwind CSS.",
    image: "/images/about.png",
    github: "https://github.com/username/blog-platform",
    live: "#",
    category: "CMS",
  },
  {
    title: "Event Booking Site",
    description: "Event booking website using Stripe and Next Auth.",
    image: "/images/s1.png",
    github: "https://github.com/username/event-booking",
    live: "#",
    category: "Fullstack",
  },
];
